# Generated by Django 4.0.4 on 2022-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
