# Generated by Django 4.0.4 on 2022-12-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0003_alter_photo_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='instructions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
