# Generated by Django 4.0.4 on 2022-12-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0004_alter_photo_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='FileModel',
        ),
    ]
